### ISSUE TITLE
No feedback when token is missing on `list` commands

### ISSUE THREAD

**Issue by KtorZ** [abailly/hdo#3]
Each command but the list ones uses the Result functor to convey a the API response and a potential error. For lists, a List `[a]` is directly used as the wrapping functor which makes it impossible to convey any error when there's one.

For instance, in [Network.DO.Net.Common](https://github.com/abailly/hdo/blob/master/src/Network/DO/Net/Common.hs#L40), an empty list is returned when a token is missing which is a bit counter-intuitive as a result from the CLI and when used as a library.

Also, for consistency in my opinion, it would be nicer to align the returned wrapping functor with the other commands, i.e. `Result [a]`. 

I am currently doing the necessary changes, do you agree ?

**Comment by abailly** [comment]
+100 :)

**Comment by KtorZ** [comment]
Closed in #4
