### ISSUE TITLE
Passing Query Meta-Parameters

### ISSUE THREAD

**Issue by KtorZ** [abailly/hdo#9]
Digital Ocean list endpoints return list of resources paginated with only 25 entities by default. It is possible to alter this behavior by passing the `page` & `per_page` query parameters with the url.

`hdo` doesn't support passing those parameters at the moment. I can pick up the issue but it's likely to result in a small breaking change for the top-level API / types.

Are you fine with that?

**Comment by abailly** [comment]
Hi Mathias, Sorry for not being very reactive. Just starting a new job, overwhelmed with meetings...

Please go ahead! Maybe you can limit the impact by providing some sensible defaults?
